app:
  message: message succesfuly sent

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: user.exchange
    routingkey: user.routingkey

server:
  port: 8081